language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
dist: xenial
sudo: true
env:
  - PYTEST=3.6.4
  - PYTEST=3.7.4
  - PYTEST=3.8.2
  - PYTEST=3.9.3
  - PYTEST=3.10.0
  - PYTEST=4.0.*
  - PYTEST=4.1.*
install:
  - "pip install -q pytest==$PYTEST"
  - "pip install -q -e ."
script: "pytest tests/"
