language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
dist: xenial
sudo: true
env:
  - PYTEST=3.6.4
  - PYTEST=3.7.4
  - PYTEST=3.8.2
  - PYTEST=3.9.3
  - PYTEST=3.10.0
  - PYTEST=4.0.*
  - PYTEST=4.1.*
  - PYTEST=4.2.*
  - PYTEST=5.*
  - PYTEST=6.*
install:
  - "pip install -q pytest==$PYTEST"
  - "pip install -q -e ."
script: "pytest tests/"

jobs:
  exclude:
    - python: "2.7"
      env: PYTEST=5.*
    - python: "2.7"
      env: PYTEST=6.*

